### ISSUE TITLE
Commentaire dans un commit

### ISSUE THREAD

**Issue by Mat1212fr** [BroMinee/PaladiumClicker#1]
Comme je suppose que les commentaires dans les commits ne sont pas transmis au développeur je mets le lien de mes questions :
https://github.com/BroMinee/PaladiumClicker/commit/266580f#commitcomment-140513191

**Comment by BroMinee** [comment]
Ahah j'aimerai bien avoir ce talent en musique mais c'est générer via IA.
Donc temps de production on est sur 5 minutes
https://app.suno.ai/song/da30304c-34e5-4aba-b9ea-6e717de74eb0

**Comment by Mat1212fr** [comment]
Nickel merci beaucoup
