### ISSUE TITLE
There isn't GitHub Pages site here

### ISSUE THREAD

**Issue by amolinarius** [BroMinee/PaladiumClicker#10]
Bonjour,
Je voulais prévenir que quand on utilise la navbar tout marche bien, mais quand on recharge la page sur autre chose que le `PalaClicker Optimizer` on a une erreur de github (There isn't a Github Pages site here).
Je pense que ça vient du fait que les pages sont censées être sur [brominee.github.io/PaladiumClicker/](https://brominee.github.io/PaladiumClicker/) seulement, et pas sur les autres pages comme `/Profil`, `/Calculator` ou `/PalaAnimation`.
J'ai un peu la flemme de trouver comment régler le problème (sinon j'aurais fait une pull request) mais je voulais quand même prévenir

**Comment by BroMinee** [comment]
Oui je connais déjà ce bug, seulement tant que j'héberge sur les GitHub Pages je ne pourrais pas fix de soucis
