### ISSUE TITLE
bug: URLs sending 404 while they shouldn't

### ISSUE THREAD

**Issue by Sylicium** [BroMinee/PaladiumClicker#15]
Explication:
Quand on se dirige depuis https://brominee.github.io/PaladiumClicker/ sur d'autres pages, l'url change et on est bien redirigé. Cependant si on essais d'aller directement sur cette url, on obtient une erreur 404.

Reproduire le bug.
1. Ouvrir https://brominee.github.io/PaladiumClicker/
2. Cliquer sur AH (ou autre)
3. Voyez l'url changer vers https://brominee.github.io/PaladiumClicker/ah , le contenu est bien update, tout fonctionne
4. Ouvrez une autre page et allez directement sur https://brominee.github.io/PaladiumClicker/ah , le contenu ne s'affiche pas, erreur 404
![image](https://github.com/BroMinee/PaladiumClicker/assets/96630108/f6741fb1-7c9c-47d6-86bd-cb27b53b8f99)

**Comment by BroMinee** [comment]
Avec la méthode actuelle, il ne met pas possible de faire en sorte que les URLs autres que [https://brominee.github.io/PaladiumClicker/](https://brominee.github.io/PaladiumClicker/) puisse se recharger sans afficher erreur 404.
Mais je suis en train de mettre en place une nouvelle URL avec un hébergement plus malléable permettant de régler ce soucis, ca devrait voir le jour dans les semaines qui arrivent.
