### ISSUE TITLE
403 Forbidden - Paladium API

### ISSUE THREAD

**Issue by LeMaitre4523** [BroMinee/PaladiumClicker#6]
Bonjour,
J'ai voulu tester le PaladiumClicker avec un profile tel que LeVraiFuze, et celui-ci ne marche pas.
La requête échoue avec cette erreur :
`{"type":"AUTHORIZATION_ERROR","message":"You are not allowed to access this resource."}`

**Comment by LeMaitre4523** [comment]
Tout est bon, j'ai compris.

**Comment by BroMinee** [comment]
Pour ceux qui se demande : "C'est une feature permettant à quelques youtubers de pouvoir désactiver la possibilité de voir leurs données publiques notamment pour le stalking"
